language: go

go:
    - 1.3

services:
    - memcached


install: go get -d -v ./... && go build -v ./... && make

before_script:  mysql -e 'create database test;' && cm-proxy &

script: "./run_test.sh"

branches:
  only:
  - master
