language: go

go:
    - 1.3

env:
    - DB=mysql

services:
    - memcached

install: go get -d -v ./... && go build -v ./... && make

before_script:
    - mysql -e "create database IF NOT EXISTS test;" -uroot
    - cm-proxy &

script: "./run_test.sh"

branches:
  only:
  - master
