language: go

go:
    - 1.3

services:
    - memcached

before_script:
  - mysql -e 'create database test;'

install: go get -d -v ./... && go build -v ./... && make


before_script: "cm-proxy &"
script: "./run_test.sh"

branches:
  only:
  - master
