language: go

go:
    - 1.3

env:
    - DB=mysql

services:
    - memcached

install: go get -d -v ./... && go build -v ./... && make

before_script:
    - mysql -e "DROP DATABASE IF EXISTS test; CREATE DATABASE test;CREATE TABLE test.tbl_test (id INT, data VARCHAR(255));" -uroot
    - cm-proxy &

script: "./run_test.sh"

branches:
  only:
  - master
